### ISSUE TITLE
Display only if enabled

### ISSUE THREAD

**Issue by goat865** [Trsnaqe/gamemode-shell-extension#1]
An option would be awesome to show the icon only if gamemode is enabled.

**Comment by Trsnaqe** [comment]
Hey, thanks for the idea. However, there is a slight challenge. I have to add a preferences widget to let users change settings outside of the top-down menu. I will try to add this feature when I am free, but it might take a while as I am busy with other projects at the moment.

Much appreciated!

**Comment by Trsnaqe** [comment]
Hello again, 
I have just updated the extension that should be satistify this feature. I am closing this issue as completed, if you come across a bug or you have a feedback after this update please open issue again. 

Please update your extension and tell me what you think!
[Try the new version](https://extensions.gnome.org/extension/7074/gamemode-shell-extension/) 

Thanks for a good feature idea again!
